'use strict';

module.exports = {
    history: getHistory()
};

function getHistory() {
    return `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sapien leo, volutpat non justo nec, sollicitudin tristique urna. Mauris lobortis rhoncus lorem, nec ultrices nisl fermentum eget. Vestibulum in velit ultricies, semper nisi non, viverra enim. Curabitur sed lacinia leo. Praesent egestas lacinia semper. Praesent lacinia tellus ut ante vestibulum, eu posuere risus eleifend. Proin vehicula augue nisl. Donec posuere neque eget odio bibendum, ac euismod quam vestibulum. Nam dictum sem aliquet egestas sollicitudin. In id auctor sapien, id consequat massa. Suspendisse urna sem, imperdiet vitae sodales vitae, sodales sit amet urna. Fusce gravida, metus ut commodo imperdiet, quam mi ullamcorper mi, sit amet fermentum ante risus et sapien. Vivamus dapibus quam eu urna fringilla pellentesque.

Nam eu mi suscipit, condimentum felis eget, dictum orci. Aenean cursus lorem leo, vitae vestibulum ex sollicitudin vel. Morbi faucibus volutpat eros, accumsan scelerisque nibh consequat ac. Nullam ut augue commodo nisl feugiat dignissim. Phasellus aliquam et erat vitae feugiat. Suspendisse bibendum semper metus. Aenean mi metus, faucibus eget consectetur nec, ultricies convallis ante. Vivamus aliquet purus vel pharetra feugiat. Vivamus dapibus, risus quis facilisis condimentum, tellus mauris vulputate tortor, quis ornare erat massa quis justo. Quisque hendrerit tellus justo, et tristique mi facilisis a. Ut placerat commodo risus et aliquam. Nullam pharetra erat venenatis vulputate maximus. Mauris convallis luctus sodales. In imperdiet dui luctus est facilisis efficitur.

Quisque quis mi id felis dapibus euismod at vel nunc. Morbi aliquet id neque id feugiat. Proin est purus, viverra in elit eget, elementum bibendum diam. Maecenas venenatis vitae urna id volutpat. Proin congue consequat leo. Ut mi dolor, ultricies quis erat ut, fermentum porttitor risus. Aliquam egestas finibus leo, in sagittis diam. Nullam massa ante, varius a fringilla id, lobortis vitae ante. Integer accumsan felis ex, ac pretium lorem blandit in. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean vel est vitae turpis interdum congue vitae id sem. Sed consequat enim vitae tellus suscipit accumsan. Nam pharetra quis felis eget finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas at felis nisl.

Ut rhoncus sapien diam, a varius enim feugiat eget. Morbi mi augue, scelerisque vel enim ac, rutrum scelerisque neque. Sed in nisl maximus felis molestie finibus eget ut urna. Nam tristique nisl quis nibh efficitur, et porttitor urna faucibus. Etiam id est sapien. Phasellus laoreet diam nibh, in gravida massa placerat vel. Nam eu massa diam. Cras ut elit velit. Maecenas tempor egestas ligula, vitae varius ex sagittis vel. Integer mattis, sapien nec elementum pretium, nibh augue vestibulum elit, quis ullamcorper magna mi non nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras dolor dolor, fermentum id massa id, ornare porttitor erat.

Proin porttitor, est eu rhoncus pulvinar, justo sem dignissim lorem, in vestibulum nisi libero at mi. Maecenas eu scelerisque ex, vitae eleifend est. Nunc ac bibendum sem. Mauris accumsan nisi ac dui viverra rutrum. Donec aliquam nibh quis neque efficitur euismod. Phasellus blandit vulputate convallis. In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam ut vulputate lectus. Donec odio mauris, aliquet quis congue facilisis, venenatis vel libero. Ut dictum diam ultrices risus imperdiet volutpat. Nam imperdiet est justo, ut interdum orci gravida quis. Fusce rutrum dui in lacus viverra semper. Praesent quis orci sed dui volutpat porta in et nibh. Suspendisse tristique scelerisque dui sit amet tempor.`
}
